settings:
  onMissingLabel: create

rules:
  issue:
    - label: feature
      matches:
        - operator: any
          conditions:
            - title: /feat/i
    - label: fix
      matches:
        - operator: any
          conditions:
            - title: /fix/i
    - label: refactor
      matches:
        - operator: any
          conditions:
            - title: /refactor/i
    - label: chore
      matches:
        - operator: any
          conditions:
            - title: /chore/i
    - label: docs
      matches:
        - operator: any
          conditions:
            - title: /docs/i
    - label: style
      matches:
        - operator: any
          conditions:
            - title: /style/i
    - label: test
      matches:
        - operator: any
          conditions:
            - title: /test/i

  pr:
    - label: feature
      matches:
        - operator: any
          conditions:
            - title: /feat/i
            - head-branch: /feat/i
    - label: fix
      matches:
        - operator: any
          conditions:
            - title: /fix/i
            - head-branch: /fix/i
    - label: refactor
      matches:
        - operator: any
          conditions:
            - title: /refactor/i
            - head-branch: /refactor/i
    - label: chore
      matches:
        - operator: any
          conditions:
            - title: /chore/i
            - head-branch: /chore/i
    - label: docs
      matches:
        - operator: any
          conditions:
            - title: /docs/i
            - head-branch: /docs/i
    - label: style
      matches:
        - operator: any
          conditions:
            - title: /style/i
            - head-branch: /style/i
    - label: test
      matches:
        - operator: any
          conditions:
            - title: /test/i
            - head-branch: /test/i
    - label: APP
      matches:
        - operator: any
          conditions:
            - changed-files: apps/app/**
    - label: WEB
      matches:
        - operator: any
          conditions:
            - changed-files: apps/web/**
