/**
 * 메시지 네이밍 규칙
 * - WEB_REQ_XXX: 웹 → 앱 요청
 * - APP_RES_XXX: 웹 ← 앱 응답
 * - APP_REQ_XXX: 앱 → 웹 요청
 * - WEB_RES_XXX: 앱 ← 웹 응답
 */
export const WEBBRIDGE_MESSAGE_TYPE = {
  /** 이미지 첨부 관련 */
  WEB_REQ_OPEN_IMAGE_PICKER: 'WEB_REQ_OPEN_IMAGE_PICKER',
  APP_RES_IMAGE_PICKER_SUCCESS: 'APP_RES_IMAGE_PICKER_SUCCESS',
  APP_RES_IMAGE_PICKER_CANCEL: 'APP_RES_IMAGE_PICKER_CANCEL',
  APP_RES_IMAGE_PICKER_ERROR: 'APP_RES_IMAGE_PICKER_ERROR',

  /**
   * 소셜 로그인 관련
   *
   * NOTE: value는 네이밍 규칙 도입 이전에 정해진 것으로, 배포된 앱과의 호환을 위해 규칙과 어긋나지만 유지한다.
   */
  WEB_REQ_SOCIAL_LOGIN: 'REQUEST_SOCIAL_LOGIN',
  APP_RES_SOCIAL_LOGIN_SUCCESS: 'SOCIAL_LOGIN_SUCCESS',
  APP_RES_SOCIAL_LOGIN_ERROR: 'SOCIAL_LOGIN_ERROR',
  WEB_REQ_LOGOUT: 'WEB_REQ_LOGOUT',

  /** 앱 → 웹: WEB_REQ_READY에 대한 공유 인텐트 payload 응답 */
  APP_RES_SHARE_INTENT: 'APP_RES_SHARE_INTENT',
  /** 웹 → 앱: 페이지 hydrate 완료, 메시지 수신 준비됨 (ACK 용도) */
  WEB_REQ_READY: 'WEB_REQ_READY',

  /** 푸시 알림 관련 */
  WEB_REQ_PUSH_PERMISSION_STATUS: 'WEB_REQ_PUSH_PERMISSION_STATUS',
  WEB_REQ_PUSH_PERMISSION: 'WEB_REQ_PUSH_PERMISSION',
  WEB_REQ_OPEN_NOTIFICATION_SETTINGS: 'WEB_REQ_OPEN_NOTIFICATION_SETTINGS',
  APP_RES_PUSH_PERMISSION_STATUS: 'APP_RES_PUSH_PERMISSION_STATUS',
  APP_RES_FCM_TOKEN: 'APP_RES_FCM_TOKEN',

  /** 딥링크 관련 */
  APP_REQ_DEEP_LINK: 'APP_REQ_DEEP_LINK',
  /** 앱 → 웹: 이미 로드된 웹뷰에서 경로 이동 (warm start 딥링크 SPA 전환용) */
  APP_REQ_NAVIGATE: 'APP_REQ_NAVIGATE',

  /** 분석 관련 — 웹뷰에서 발생한 사용자 행동을 네이티브 Firebase Analytics 로 전달 */
  WEB_REQ_LOG_ANALYTICS_EVENT: 'WEB_REQ_LOG_ANALYTICS_EVENT',

  /** 토큰 갱신 — 웹에서 토큰 갱신 후 앱 SecureStore 동기화 */
  WEB_REQ_TOKEN_REFRESHED: 'WEB_REQ_TOKEN_REFRESHED',

  /** 뱃지 관련 — 웹이 읽음 처리 후 앱 아이콘 뱃지 수를 동기화 */
  WEB_REQ_SET_BADGE: 'WEB_REQ_SET_BADGE',

  /** 인스타그램 스토리 공유 — 웹에서 만든 영수증 이미지를 네이티브가 스토리 편집 화면으로 전달 */
  WEB_REQ_SHARE_INSTAGRAM_STORY: 'WEB_REQ_SHARE_INSTAGRAM_STORY',
  APP_RES_SHARE_INSTAGRAM_STORY: 'APP_RES_SHARE_INSTAGRAM_STORY',

  /** 앱 업데이트 유도 — 플랫폼에 맞는 스토어 상세 페이지 열기 */
  WEB_REQ_OPEN_STORE: 'WEB_REQ_OPEN_STORE',
} as const;

export const PUSH_NOTIFICATION_TYPE = {
  TOURNAMENT_JOINED: 'TOURNAMENT_JOINED',
  TOURNAMENT_ITEM_ADDED: 'TOURNAMENT_ITEM_ADDED',
  ITEM_PARSING_COMPLETED: 'ITEM_PARSING_COMPLETED',
  ITEM_PARSING_INCOMPLETE: 'ITEM_PARSING_INCOMPLETE',
  ITEM_PARSING_FAILED: 'ITEM_PARSING_FAILED',
} as const;

export const WEB_REQ_READY_PAYLOAD_TYPE = {
  SHARE_INTENT: 'SHARE_INTENT',
} as const;
